/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSandboxRouteImport } from './routes/api/sandbox'
import { Route as AuthedProjectsIndexRouteImport } from './routes/_authed/projects/index'
import { Route as ApiSandboxStatusRouteImport } from './routes/api/sandbox/status'
import { Route as ApiSandboxInitRouteImport } from './routes/api/sandbox/init'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects/$projectId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxRoute = ApiSandboxRouteImport.update({
  id: '/api/sandbox',
  path: '/api/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsIndexRoute = AuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSandboxStatusRoute = ApiSandboxStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiSandboxRoute,
} as any)
const ApiSandboxInitRoute = ApiSandboxInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => ApiSandboxRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/api/sandbox/init': typeof ApiSandboxInitRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
  '/projects': typeof AuthedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/api/sandbox/init': typeof ApiSandboxInitRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
  '/projects': typeof AuthedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/api/sandbox': typeof ApiSandboxRouteWithChildren
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRoute
  '/api/sandbox/init': typeof ApiSandboxInitRoute
  '/api/sandbox/status': typeof ApiSandboxStatusRoute
  '/_authed/projects/': typeof AuthedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/sandbox'
    | '/projects/$projectId'
    | '/api/sandbox/init'
    | '/api/sandbox/status'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/sandbox'
    | '/projects/$projectId'
    | '/api/sandbox/init'
    | '/api/sandbox/status'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/api/sandbox'
    | '/_authed/projects/$projectId'
    | '/api/sandbox/init'
    | '/api/sandbox/status'
    | '/_authed/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiSandboxRoute: typeof ApiSandboxRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox': {
      id: '/api/sandbox'
      path: '/api/sandbox'
      fullPath: '/api/sandbox'
      preLoaderRoute: typeof ApiSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/sandbox/status': {
      id: '/api/sandbox/status'
      path: '/status'
      fullPath: '/api/sandbox/status'
      preLoaderRoute: typeof ApiSandboxStatusRouteImport
      parentRoute: typeof ApiSandboxRoute
    }
    '/api/sandbox/init': {
      id: '/api/sandbox/init'
      path: '/init'
      fullPath: '/api/sandbox/init'
      preLoaderRoute: typeof ApiSandboxInitRouteImport
      parentRoute: typeof ApiSandboxRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRoute
  AuthedProjectsIndexRoute: typeof AuthedProjectsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRoute,
  AuthedProjectsIndexRoute: AuthedProjectsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiSandboxRouteChildren {
  ApiSandboxInitRoute: typeof ApiSandboxInitRoute
  ApiSandboxStatusRoute: typeof ApiSandboxStatusRoute
}

const ApiSandboxRouteChildren: ApiSandboxRouteChildren = {
  ApiSandboxInitRoute: ApiSandboxInitRoute,
  ApiSandboxStatusRoute: ApiSandboxStatusRoute,
}

const ApiSandboxRouteWithChildren = ApiSandboxRoute._addFileChildren(
  ApiSandboxRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiSandboxRoute: ApiSandboxRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
